name: Android Build
on:
  push:
    branches:
      - 'master'
jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Run tests
        run: ./gradlew testDebug --stacktrace